#+TITLE: Monorepo for Emacs packages and Spacemacs layers by @plexus

Most of these packages are not on MELPA, they are my various tinkerings and experiments. I do run a private ELPA repository for easy consumption.

#+BEGIN_SRC emacs-lisp
(add-to-list 'package-archives '("plexmacs" . "https://plexus.github.io/plexmacs-elpa/packages/") t)
#+END_SRC

* Packages
** clj-ns-name

Set the buffer name of Clojure buffers to the Clojure namespace name.

** pprint-to-buffer

Brings CIDER's C-c C-p to elisp

** sesman-table

An alternative to the now disappeared `cider-connection-browser`

** header2

Taken off the internet, automatic headers for Emacs Lisp.

* Layers

#+BEGIN_SRC emacs-lisp
  (add-to-list 'dotspacemacs-configuration-layer-path "/home/arne/github/plexmacs/layers/")
#+END_SRC

** lambdaisland

Lambda Island look and feel, and other Lambda Island specific code.

** plexus-editing

Various coding UX tweaks.

** plexus-defaults

Better emacs defaults.

** plexus-clojure-extras

- Use clj-ns-name
- Bind < and > to slurp / barf
- Enable aggressive indent mode in Clojure buffers
* Resources
- [[https://github.com/noctuid/evil-guide#keybindings-and-states][evil-guide: bindings and state]] Probably the best explanation of the mess that is the evil keybinding system.
