#!/bin/bash

echo ===== Syncing Plexmacs repo =====

git add -A
git commit -m 'sync'
git push

echo ===== Syncing Plexmacs ELPA =====

cd ../plexmacs-elpa
./sync

# emacsclient -e '(auto-package-update-now)'
